services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      #POSTGRES_HOST_AUTH_METHOD: md5
      #POSTGRES_INITDB_ARGS: --auth-host=md5
    ports:
      - '5432:5432'